{
    'name': 'opsol_marinebroderies',
    'version': '1.3.13',
    'summary': 'Add custom modification for Marine Broderies',
    'description': 'Add custom modification for Marine Broderies',
    'category': 'Uncategorized',
    'author': 'OpenSolution',
    'website': 'https://www.opensolution.mc',
    'license': 'LGPL-3',
    'depends': ['base', 'purchase', 'sale_stock', 'sale_purchase', 'purchase_stock', 'opsol_catalog_kanban_width', 'crm', 'sale_delivery_state'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/purchase_order_view.xml',
        'views/sale_order_view.xml',
        'views/stock_picking_view.xml',
        'views/product_product_view.xml',
        'views/type_broderie_views.xml',
        'views/crm_team_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
}
