{
    'name': 'opsol_marinebroderies',
    'version': '1.2',
    'summary': 'Add custom modification for Marine Broderies',
    'description': 'Add custom modification for Marine Broderies',
    'category': 'Uncategorized',
    'author': 'OpenSolution',
    'website': 'https://www.opensolution.mc',
    'license': 'LGPL-3',
    'depends': ['base', 'purchase', 'sale_stock', "sale_purchase", "purchase_stock", "opsol_catalog_kanban_width"],
    'data': [
        'security/res_groups.xml',
        'views/purchase_order_view.xml',
        'views/sale_order_view.xml',
        'views/stock_picking_view.xml',
        'views/product_product_view.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
}
