from . import stock_picking
from . import purchase_order_line
from . import purchase_order
from . import stock_move
from . import sale_order_line
from . import product_template
from . import product_product
from . import product_template_attribute_value
from . import type_broderie
from . import sale_order
from . import crm_team
